/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in as admin
         * @description POST /auth/login — Exchange the admin password for a bearer token.
         *     Body: { password }. Returns { token } valid for 24 hours.
         */
        post: operations["d19b53098572bc1c035e34307fd6a7d3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/danbooru/category-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List category mappings
         * @description GET /danbooru/category-mappings — All Danbooru→gallery category mappings.
         */
        get: operations["22d9bcf4f926e3a9b39fcb32127a38ba"];
        put?: never;
        /**
         * Create a category mapping
         * @description POST /danbooru/category-mappings — Map a Danbooru category to a gallery
         *     category. Body: { danbooru_category_id, danbooru_category_name, gallery_category_id }.
         */
        post: operations["e6f08412d1beec7a2bc9e36fdeadd2f8"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/danbooru/category-mappings/{danbooru_category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a category mapping
         * @description DELETE /danbooru/category-mappings/{danbooru_category_id} — Remove a mapping.
         */
        delete: operations["001c8226c2296eb22a0d32d80a4e7c50"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/danbooru/tag-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tag name mappings
         * @description GET /danbooru/tag-mappings — All Danbooru→gallery tag-name mappings.
         */
        get: operations["dc012fab6f7b6f142e9de0fd0b2819d0"];
        put?: never;
        /**
         * Create a tag name mapping
         * @description POST /danbooru/tag-mappings — Map a Danbooru tag name to a gallery tag name.
         *     Body: { danbooru_tag, gallery_tag }.
         */
        post: operations["c74f706262d1d4bde1d22ca6ffa8f306"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/danbooru/tag-mappings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a tag name mapping
         * @description PUT /danbooru/tag-mappings/{id} — Update a tag-name mapping.
         *     Body: { danbooru_tag, gallery_tag }.
         */
        put: operations["a2c2f92cb7e1ace2f9bfad750dcf698a"];
        post?: never;
        /**
         * Delete a tag name mapping
         * @description DELETE /danbooru/tag-mappings/{id} — Remove a tag-name mapping.
         */
        delete: operations["4d60bfb4f3c69d92f7f8337102474e9f"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/duplicates/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest duplicate report
         * @description GET /duplicates/report — The latest duplicate-scan report, with dismissed
         *     pairs filtered out and each pair enriched with media file names/hashes.
         */
        get: operations["cf87d7c7b3fda80a991907a425d0fc0f"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/duplicates/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a duplicate scan
         * @description POST /duplicates/scan — Run the perceptual-hash duplicate scanner and
         *     return summary stats (images compared, candidates, duplicates found).
         */
        post: operations["1723375dae6967be7242b04b58a65e47"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/duplicates/dismissals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss a duplicate pair
         * @description POST /duplicates/dismissals — Dismiss a pair of media items as not-duplicates.
         *     Body: { media_id_1, media_id_2 }.
         */
        post: operations["70b30de80982dfb5b34e060d84757c9f"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/page/{page}/{per_page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of media
         * @description GET /media/page/{page}[/{per_page}] — A page of media items.
         *     Returns { items, total_pages, current_page }. per_page is clamped to 1..200.
         */
        get: operations["e36edad483d19175abc37f3425d78d4f"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/untagged/{page}/{per_page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of untagged media
         * @description GET /media/untagged/{page}[/{per_page}] — A page of media with no tags.
         */
        get: operations["e6ddd2db1d30f900c523e5d4f4c5929e"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/with-tags/{tag_list}/{page}/{per_page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of media filtered by tags
         * @description GET /media/with-tags/{tag_list}/{page}[/{per_page}] — A page of media
         *     filtered by a comma-separated tag list; a leading '-' excludes a tag
         *     (e.g. "cat,-dog"). Returns { items, total_pages, current_page }.
         */
        get: operations["6c7638b89708ed00c34ab4c7359dee21"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A single media item
         * @description GET /media/{media_id} — A single media item by ID.
         */
        get: operations["93a3cbb87461ec463456431a291b42b7"];
        put?: never;
        post?: never;
        /**
         * Delete a media item
         * @description DELETE /media/{media_id} — Delete a media item (DB row, file, thumbnails).
         */
        delete: operations["bc2c9367eface3854e5a3f5dd85e4c60"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A random media item
         * @description GET /media/random — A single random media item.
         */
        get: operations["c1b812df796aa1e537afca9600c6990a"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Total media count
         * @description GET /media/count — The total media count, as { count }.
         */
        get: operations["1e179cec05cf0eef3555de51a0a686c6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch-fetch media by IDs
         * @description POST /media/by-ids — Get multiple media items by an array of IDs.
         *     Body: { ids: int[] } (max 200). Missing IDs are silently skipped.
         *     A public batched read (uses POST only to carry a large id list).
         */
        post: operations["b370f569a77c422bb41e6d7977479e4a"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk-delete media items
         * @description POST /media/bulk-delete — Delete one or more media items by ID.
         *     Body: { media_ids: int[] }. Returns the deleted and failed ID lists.
         */
        post: operations["6aedfe7046057e8d9cc4373a58f46be3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A media item's tags
         * @description GET /media/{media_id}/tags — Tags applied to a media item. Cached.
         */
        get: operations["ab04a8f3ded716c3f8147a45937b12ab"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Add tags to a media item
         * @description PATCH /media/{media_id}/tags — Apply tags to a media item (implications
         *     resolved). Body: { tag_ids: int[] }. Returns the item's updated tag list.
         *     Public (anyone may tag).
         */
        patch: operations["986db528dbc801613c7e3a5e5028e29b"];
        trace?: never;
    };
    "/media/{media_id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a tag from a media item
         * @description DELETE /media/{media_id}/tags/{tag_id} — Remove a tag from a media item.
         *     Returns the item's updated tag list. Public (anyone may tag).
         */
        delete: operations["5a455845a66f449bce743bbbf21aaec9"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}/danbooru-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Danbooru tags for a media item
         * @description POST /media/{media_id}/danbooru-tags — Import tags from Danbooru for a
         *     media item. Body: { danbooru_post_id? }. With a post ID, imports directly;
         *     otherwise auto-looks-up by MD5 hash then IQDB visual similarity.
         */
        post: operations["6740f36bf05702b4a32eb09cb780f124"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Application and API version
         * @description GET /version — The running application and API contract versions.
         */
        get: operations["b58bcc79d28366e5312ce30aada568ae"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The OpenAPI 3.1 specification
         * @description GET /openapi.json — The generated OpenAPI 3.1 document.
         *
         *     Serves the spec committed to the repo (regenerated with `composer docs`),
         *     so production does not depend on swagger-php being installed.
         */
        get: operations["af9e6f6d2c7c09dec463f379e35acd1b"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interactive API reference (Scalar)
         * @description GET /docs — The interactive API reference (Scalar), pointed at the spec.
         */
        get: operations["7ce25c6fca2a2bd67d758cee99044f42"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tag categories
         * @description GET /tag-categories — All tag categories.
         */
        get: operations["344bd2707a98746738eb6b0b3ed143ff"];
        put?: never;
        /**
         * Create a tag category
         * @description POST /tag-categories — Create a tag category. Returns the created category.
         *     Body: { category_name, category_short, color?, description?, sort_order? }
         */
        post: operations["dc114b35e6a6392f6c75717bf3f23651"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag-categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a tag category
         * @description PUT /tag-categories/{category_id} — Update a tag category.
         *     Returns the updated category. Body: same fields as create.
         */
        put: operations["2cda0d143e8dfc92355bb0452d037f19"];
        post?: never;
        /**
         * Delete a tag category
         * @description DELETE /tag-categories/{category_id} — Delete a category that has no tags.
         */
        delete: operations["c1c34eafc2deb4bbe13b3114487847b6"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tags
         * @description GET /tags — All tags (id, name, category). Cached.
         */
        get: operations["914076a044e72c93ac5e739f052b71e5"];
        put?: never;
        /**
         * Create a tag
         * @description POST /tags — Create a tag. Body: { tag_name, category_id? (default 1) }.
         *     Returns the created tag.
         */
        post: operations["595b6c6e60d4db82867b9aac8fccd85c"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/display": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tags with category and usage counts
         * @description GET /tags/display — All tags with category and usage/implication counts,
         *     for the tags-management page. Cached.
         */
        get: operations["2ea1bafb5afae11c3f755af5f21d4a9c"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A single tag
         * @description GET /tags/{tag_id} — A single tag by ID.
         */
        get: operations["516d4cb67ae4252a9bc173311de5e68f"];
        /**
         * Update a tag
         * @description PUT /tags/{tag_id} — Rename and/or recategorize a tag.
         *     Body: { tag_name, category_id? (default 1) }. Returns the updated tag.
         */
        put: operations["25adaf316f2f4f1b67d2a97fc0c51be6"];
        post?: never;
        /**
         * Delete a tag
         * @description DELETE /tags/{tag_id} — Delete a tag.
         *     DELETE /tags/{tag_id}/migrate-to/{target_tag_id} — migrate this tag's media
         *     to the target first, then delete this tag.
         */
        delete: operations["f027b0d6d7e013be44cf6be55a027706"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}/migrate-to/{target_tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Migrate a tag's media to another tag, then delete it */
        delete: operations["3fc0029729ae4febe19a3d71da0d5cd6"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag_id}/migrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Migrate a tag into another
         * @description POST /tags/{tag_id}/migrate — Move all media from this tag to the target,
         *     then delete this tag. Body: { target_tag_id }.
         */
        post: operations["cdb54be9af6ceae381d97625192996ca"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag-implications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tag implications
         * @description GET /tag-implications — All tag implications. Cached.
         */
        get: operations["a0ce21a9789fd654d9f7b164491bc60b"];
        put?: never;
        /**
         * Create a tag implication
         * @description POST /tag-implications — Add "tag_id implies implied_tag_id".
         *     Body: { tag_id, implied_tag_id }. Rejects cycles and self-implication.
         *     Returns the created implication.
         */
        post: operations["9ed70fe6fc2fe1fdc19be3a497665936"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag-implications/{tag_id}/{implied_tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a tag implication
         * @description DELETE /tag-implications/{tag_id}/{implied_tag_id} — Remove an implication.
         */
        delete: operations["381181baeba3505869a9c5d513610990"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload media (create)
         * @description POST /media — Upload one or more files (multipart/form-data with files[]).
         *     Media type is auto-detected from each file's extension.
         */
        post: operations["da47a0a080049a9a1698c19e03cae289"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Outcome of a bulk media delete. */
        BulkDeleteResult: {
            /** @description IDs successfully deleted. */
            deleted?: number[];
            /** @description IDs that could not be deleted. */
            failed?: number[];
            total_deleted?: number;
        };
        /** @description A Danbooru-to-gallery category mapping. */
        CategoryMapping: {
            danbooru_category_id?: number;
            danbooru_category_name?: string;
            gallery_category_id?: number;
            gallery_category_name?: string | null;
        };
        /** @description A count wrapper. */
        Count: {
            count?: number;
        };
        /** @description Outcome of a Danbooru tag import. */
        DanbooruFetchResult: {
            /** @description The media item's tags after import. */
            tags?: components["schemas"]["Tag"][];
            /** @description The full tag list (new tags may have been created). */
            all_tags?: components["schemas"]["Tag"][];
            /** @description Lookup method used (md5 / iqdb / post). */
            method?: string;
            tags_applied?: number;
            tags_created?: number;
        };
        /** @description A dismissed duplicate pair. */
        DismissResult: {
            dismissed?: boolean;
            media_id_1?: number;
            media_id_2?: number;
        };
        /** @description A duplicate media pair with similarity scores. */
        DuplicateMatch: {
            media_1?: {
                media_id?: number;
                file_name?: string;
                hash?: string;
            };
            media_2?: {
                media_id?: number;
                file_name?: string;
                hash?: string;
            };
            /** @description Hamming distance between fingerprints. */
            distance?: number | null;
            /**
             * Format: float
             * @description Structural similarity (SSIM) score.
             */
            ssim?: number | null;
        };
        /** @description The latest duplicate-detection report. */
        DuplicateReport: {
            report_file?: string;
            /** @description ISO timestamp the report was generated. */
            generated_at?: string | null;
            images_compared?: number | null;
            duplicates_found?: number;
            matches?: components["schemas"]["DuplicateMatch"][];
        };
        /** @description Standard error envelope. */
        ErrorResponse: {
            /** @description Stable PascalCase machine code (e.g. MediaNotFound). */
            error?: string;
            /** @description Human-readable message for display. */
            message?: string;
        };
        /** @description Issued admin bearer token. */
        LoginResponse: {
            /** @description Bearer token, valid for 24 hours. */
            token?: string;
        };
        /** @description A paginated page of media items. */
        MediaPage: {
            items?: components["schemas"]["Media"][];
            total_pages?: number;
            current_page?: number;
        };
        /** @description Outcome of a tag migration. */
        MigrateResult: {
            migrated?: boolean;
            /** @description The source tag (now deleted). */
            source_tag_id?: number;
            /** @description The target tag that received the media. */
            target_tag_id?: number;
        };
        /** @description Duplicate-scan summary statistics. */
        ScanResult: {
            success?: boolean;
            message?: string;
            images_compared?: number;
            lsh_candidates?: number;
            duplicates_found?: number;
            /**
             * Format: float
             * @description Execution time in seconds.
             */
            execution_time?: number;
        };
        /** @description A tag implication (tag -> implied tag). */
        TagImplication: {
            tag_id?: number;
            tag_name?: string;
            implied_tag_id?: number;
            implied_tag_name?: string;
        };
        /** @description A tag with category name and usage counts. */
        TagListItem: {
            tag_id?: number;
            tag_name?: string;
            category_id?: number;
            category_name?: string | null;
            /** @description Number of media items with this tag. */
            media_count?: number;
            /** @description Number of implications originating from this tag. */
            implication_count?: number;
        };
        /** @description A Danbooru-to-gallery tag name mapping. */
        TagMapping: {
            id?: number;
            danbooru_tag?: string;
            gallery_tag?: string;
        };
        /** @description Per-file upload outcome. */
        UploadResult: {
            file_name?: string;
            /** @enum {string} */
            status?: "success" | "duplicate" | "error";
            /** @description New media ID (on success). */
            id?: number;
            /** @description Existing media ID (on duplicate). */
            existing_id?: number;
            /** @description MD5 hash of the file. */
            hash?: string;
            /** @description Failure reason (on error). */
            message?: string;
            /** @description Whether Danbooru tags were found. */
            tags_found?: boolean;
            /** @description Number of tags applied from Danbooru. */
            tags_applied?: number;
            /** @description Danbooru lookup method used (md5/iqdb). */
            tags_method?: string;
        };
        /** @description Aggregate upload result. */
        UploadSummary: {
            results?: components["schemas"]["UploadResult"][];
            total_uploaded?: number;
            total_duplicates?: number;
            total_failed?: number;
            /** @description Total Danbooru tags applied (only when fetch_tags was set). */
            total_tags_applied?: number;
        };
        /** @description Application and API version. */
        VersionResponse: {
            /** @description Application version (SemVer). */
            version?: string;
            /** @description HTTP API contract version (SemVer). */
            api_version?: string;
        };
        /** @description A media item (image or video). */
        Media: {
            media_id?: number;
            /** @enum {string} */
            media_type?: "image" | "video";
            file_name?: string;
            /** @description Unix timestamp the file was ingested. */
            file_time?: number;
            /** @description MD5 hash of the file contents. */
            hash?: string;
            /** @description Perceptual fingerprint (images only). */
            bits_fingerprint?: string;
            width?: number;
            height?: number;
            /**
             * Format: float
             * @description Duration in seconds; 0 for still images.
             */
            duration?: number;
            /** @description File size in bytes. */
            file_size?: number;
        };
        /** @description A tag. */
        Tag: {
            tag_id?: number;
            category_id?: number;
            tag_name?: string;
        };
        /** @description A tag category (color, shortcode, sort order). */
        TagCategory: {
            category_id?: number;
            category_name?: string;
            /** @description Short code (<= 5 chars) used in tag prefixes. */
            category_short?: string;
            /** @description Bulma/extended palette color name. */
            color?: string;
            description?: string;
            sort_order?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    d19b53098572bc1c035e34307fd6a7d3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Issued token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description InvalidPassword */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description TooManyAttempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AdminNotConfigured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "22d9bcf4f926e3a9b39fcb32127a38ba": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category mappings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryMapping"][];
                };
            };
        };
    };
    e6f08412d1beec7a2bc9e36fdeadd2f8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    danbooru_category_id: number;
                    danbooru_category_name: string;
                    gallery_category_id: number;
                };
            };
        };
        responses: {
            /** @description The created mapping */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryMapping"];
                };
            };
            /** @description InvalidInput */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description CategoryNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "001c8226c2296eb22a0d32d80a4e7c50": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                danbooru_category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description InvalidInput */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    dc012fab6f7b6f142e9de0fd0b2819d0: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag name mappings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagMapping"][];
                };
            };
        };
    };
    c74f706262d1d4bde1d22ca6ffa8f306: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    danbooru_tag: string;
                    gallery_tag: string;
                };
            };
        };
        responses: {
            /** @description The created mapping */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagMapping"];
                };
            };
            /** @description InvalidInput / DuplicateMapping */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    a2c2f92cb7e1ace2f9bfad750dcf698a: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    danbooru_tag: string;
                    gallery_tag: string;
                };
            };
        };
        responses: {
            /** @description The updated mapping */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagMapping"];
                };
            };
            /** @description InvalidInput / DuplicateMapping */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "4d60bfb4f3c69d92f7f8337102474e9f": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description InvalidInput */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cf87d7c7b3fda80a991907a425d0fc0f: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateReport"];
                };
            };
            /** @description NoReportsFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "1723375dae6967be7242b04b58a65e47": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResult"];
                };
            };
            /** @description ScanFailed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "70b30de80982dfb5b34e060d84757c9f": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    media_id_1: number;
                    media_id_2: number;
                };
            };
        };
        responses: {
            /** @description Dismissed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DismissResult"];
                };
            };
            /** @description InvalidInput */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    e36edad483d19175abc37f3425d78d4f: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page: number;
                per_page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPage"];
                };
            };
            /** @description InvalidPageNumber */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    e6ddd2db1d30f900c523e5d4f4c5929e: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page: number;
                per_page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of untagged media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPage"];
                };
            };
            /** @description InvalidPageNumber */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "6c7638b89708ed00c34ab4c7359dee21": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comma-separated tag names; a leading '-' excludes (e.g. cat,-dog). */
                tag_list: string;
                page: number;
                per_page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPage"];
                };
            };
            /** @description NoValidTagsSupplied */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "93a3cbb87461ec463456431a291b42b7": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The media item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description MediaNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bc2c9367eface3854e5a3f5dd85e4c60: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description MediaNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    c1b812df796aa1e537afca9600c6990a: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A random media item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description MediaNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "1e179cec05cf0eef3555de51a0a686c6": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Count"];
                };
            };
        };
    };
    b370f569a77c422bb41e6d7977479e4a: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: number[];
                };
            };
        };
        responses: {
            /** @description Matching media items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"][];
                };
            };
            /** @description InvalidInput */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "6aedfe7046057e8d9cc4373a58f46be3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    media_ids: number[];
                };
            };
        };
        responses: {
            /** @description Deletion outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResult"];
                };
            };
            /** @description InvalidInput */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ab04a8f3ded716c3f8147a45937b12ab: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description MediaDoesNotExist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "986db528dbc801613c7e3a5e5028e29b": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tag_ids: number[];
                };
            };
        };
        responses: {
            /** @description Updated tag list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description MediaDoesNotExist / TagDoesNotExist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "5a455845a66f449bce743bbbf21aaec9": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated tag list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description MediaDoesNotExist / CouldNotFindTag */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "6740f36bf05702b4a32eb09cb780f124": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    danbooru_post_id?: number | null;
                };
            };
        };
        responses: {
            /** @description Import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DanbooruFetchResult"];
                };
            };
            /** @description MediaDoesNotExist / NotFoundOnDanbooru */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description DanbooruNotConfigured */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    b58bcc79d28366e5312ce30aada568ae: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    af9e6f6d2c7c09dec463f379e35acd1b: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI document (JSON) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Spec not generated */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "7ce25c6fca2a2bd67d758cee99044f42": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML documentation page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "344bd2707a98746738eb6b0b3ed143ff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagCategory"][];
                };
            };
        };
    };
    dc114b35e6a6392f6c75717bf3f23651: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    category_name: string;
                    category_short: string;
                    color?: string;
                    description?: string;
                    sort_order?: number;
                };
            };
        };
        responses: {
            /** @description The created category */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagCategory"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "2cda0d143e8dfc92355bb0452d037f19": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    category_name: string;
                    category_short: string;
                    color?: string;
                    description?: string;
                    sort_order?: number;
                };
            };
        };
        responses: {
            /** @description The updated category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagCategory"];
                };
            };
            /** @description CategoryNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    c1c34eafc2deb4bbe13b3114487847b6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CategoryInUse */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description CategoryNotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "914076a044e72c93ac5e739f052b71e5": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
        };
    };
    "595b6c6e60d4db82867b9aac8fccd85c": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tag_name: string;
                    /** @default 1 */
                    category_id?: number;
                };
            };
        };
        responses: {
            /** @description The created tag */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description InvalidTagName / TagAlreadyExists */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "2ea1bafb5afae11c3f755af5f21d4a9c": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags with counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListItem"][];
                };
            };
        };
    };
    "516d4cb67ae4252a9bc173311de5e68f": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description TagDoesNotExist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "25adaf316f2f4f1b67d2a97fc0c51be6": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tag_name: string;
                    /** @default 1 */
                    category_id?: number;
                };
            };
        };
        responses: {
            /** @description The updated tag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description TagDoesNotExist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    f027b0d6d7e013be44cf6be55a027706: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description TagDoesNotExist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "3fc0029729ae4febe19a3d71da0d5cd6": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
                /** @description Migrate media to this tag before deleting. */
                target_tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Migrated and deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description TagDoesNotExist / MigrationTargetDoesNotExist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cdb54be9af6ceae381d97625192996ca: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_tag_id: number;
                };
            };
        };
        responses: {
            /** @description Migration result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrateResult"];
                };
            };
            /** @description TagDoesNotExist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    a0ce21a9789fd654d9f7b164491bc60b: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All implications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagImplication"][];
                };
            };
        };
    };
    "9ed70fe6fc2fe1fdc19be3a497665936": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tag_id: number;
                    implied_tag_id: number;
                };
            };
        };
        responses: {
            /** @description The created implication */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagImplication"];
                };
            };
            /** @description CannotImplySelf / CycleDetected */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description TagDoesNotExist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "381181baeba3505869a9c5d513610990": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
                implied_tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description InvalidTagID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    da47a0a080049a9a1698c19e03cae289: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    "files[]"?: string[];
                    /** @description Fetch Danbooru tags for uploaded images. */
                    fetch_tags?: boolean;
                };
            };
        };
        responses: {
            /** @description Upload result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSummary"];
                };
            };
            /** @description NoFilesUploaded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
